backend:
  name: git-gateway
  branch: main

media_folder: "imagens"         # pasta onde os arquivos serão salvos
public_folder: "/imagens"       # caminho de acesso no navegador

collections:
  - name: "plantas"
    label: "Plantas Tóxicas"
    folder: "plantas"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Nome da Planta", widget: "string" }
      - { name: "descricao", label: "Descrição", widget: "text" }
      - { name: "imagem", label: "Imagem", widget: "image" }

  - name: "sobre"
    label: "Sobre o Projeto"
    files:
      - file: "_data/sobre.md"
        label: "Informações do Projeto"
        name: "sobre"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
          - { name: "descricao", label: "Descrição", widget: "text" }
          - { name: "email", label: "E-mail", widget: "string" }
          - { name: "instagram", label: "Instagram", widget: "string" }
          - label: "Imagens da Equipe"
            name: "imagens"
            widget: "list"
            fields:
              - { name: "imagem", label: "Imagem", widget: "image" }
              - { name: "legenda", label: "Legenda", widget: "string" }