backend:
  name: auth0
  login: true
  auth0:
    domain: dev-0chyajgytueknun3.us.auth0.com
    client_id: 1WOT2mTRPSEjDnTfTuOMPVrJEsub7beN

media_folder: "static/img"
public_folder: "/img"

media_library:
  name: uploadcare

collections:
  - name: "plantas"
    label: "Plantas"
    folder: "conteudo/plantas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome Popular", name: "nome_popular", widget: "string" }
      - { label: "Nome Científico", name: "nome_cientifico", widget: "string" }
      - { label: "Toxicidade", name: "toxicidade", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "image" }